# -*- coding: utf-8 -*-
"""Limpieza de tesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvVE1m12jzS7rkaIwFU3XtEQB4CDcwKg
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from imblearn.over_sampling import SMOTE

#----------------------------------------------
#1.Carga y Preparación del Conjunto de datos (Fase CRIPS-DM)
#----------------------------------------------

print("Cargando el conjunto de datos PaySim...")
df = pd.read_csv("PAYSIM.csv")

df_clean = df[df['type'].isin(['TRANSFER', 'CASH_OUT'])].copy()

#----------------------------------------------
#2. Ingeniría de Características (Feature Engineering)
#----------------------------------------------
print("Ejecutando ingeniería de características...")
df_clean = df[df['type'].isin(['TRANSFER', 'CASH_OUT'])].copy()

df_clean['errorBalanceOrig'] = df_clean['oldbalanceOrg'] - df_clean['amount'] - df_clean['newbalanceOrig']
df_clean['errorBalanceDest'] = df_clean['oldbalanceDest'] + df_clean['amount'] - df_clean['newbalanceDest']

df_clean = pd.get_dummies(df_clean, columns=['type'], drop_first=True)

features = ['step', 'amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest', 'errorBalanceOrig', 'errorBalanceDest', 'type_TRANSFER' ]


X = df_clean[features]
y = df_clean['isFraud']

#----------------------------------------------
#3. Partición de Datos (Prevención estricta de Data Leakage)
#----------------------------------------------
print("Dividiendo los datos en conjuntos de Entrenamiento (80%) y Prueba (20%)...")

# Drop rows where 'y' is NaN to handle the ValueError in stratify
not_nan_indices = y.dropna().index
X_cleaned = X.loc[not_nan_indices]
y_cleaned = y.loc[not_nan_indices]

X_train, X_test, y_train, y_test = train_test_split(
    X_cleaned, y_cleaned, test_size=0.20, random_state=42, stratify=y_cleaned
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

#----------------------------------------------
#4. Balanceo de Clases Mediante SMOTE(Exclusivo en Set de Entrenamiento)
#----------------------------------------------

print("Aplicando SMOTE unicamente al conjunto de entrenamiento...")
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train_scaled, y_train)

#----------------------------------------------
#5. Modelado Predictivo (Variable Independiente - Dimensiones)
#----------------------------------------------
results_summary = {}

# Dimension A: Regresión Logística
print("Entrenando Modelo: Regresión Logística")
lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train_res, y_train_res)
lr_preds = lr_model.predict(X_test_scaled)
lr_probs = lr_model.predict_proba(X_test_scaled)[0:, 1]

# Dimension B: Random Forest
print("Entrenando Modelo: Random Forest")
rf = RandomForestClassifier(random_state=42)
rf.fit(X_train_res, y_train_res)

# Dimensión C: Isolation Forest (No Supervisado)
print("Entrenando modelo: Isolation Forest...")
# Se entrena con los datos normales del set de entrenamiento escalado
X_train_normal = X_train_scaled[y_train == 0]
if_model = IsolationForest(contamination=0.001, random_state=42, n_jobs=-1)
if_model.fit(X_train_normal)

# Evaluación externa del Isolation Forest usando el set de prueba
# Mapeo: -1 indica anomalía (1 en isFraud), 1 indica normalidad (0 en isFraud)
if_scores = if_model.decision_function(X_test_scaled)
if_preds = if_model.predict(X_test_scaled)
if_preds_binary = np.where(if_preds == -1, 1, 0)

#----------------------------------------------
#6. Evaluación y Comparacion de los Resultados (Variable Dependiente - Indicadores)
#----------------------------------------------

models = {
    'Regresión Logística': (lr_preds, lr_probs),
    'Random Forest': (rf_preds, rf_probs),
    'Isolation Forest': (if_preds_binary, -if_scores) # Se invierte el score para métrica ROC-AUC
}

print("\n" + "="*50 + "\nMATRIZ COMPARATIVA DE RENDIMIENTO FINANCIERO\n" + "="*50)

for name, (preds, probs) in models.items():
    cm = confusion_matrix(y_test, preds)
    tn, fp, fn, vp = cm.ravel()

    recall = vp / (vp + fn) if (vp + fn) > 0 else 0
    precision = vp / (vp + fp) if (vp + fp) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    auc = roc_auc_score(y_test, probs)

    results_summary[name] = [vp, fp, fn, tn, round(precision, 4), round(recall, 4), round(f1, 4), round(auc, 4)]

    print(f"\nIndicadores para {name}:")
    print(f"  Verdaderos Positivos (Alertas Correctas): {vp}")
    print(f"  Falsos Positivos (Alertas Innecesarias): {fp}")
    print(f"  Falsos Negativos (Casos Omitidos): {fn}")
    print(f"  Sensibilidad (Recall): {round(recall*100, 2)}%")
    print(f"  Precisión: {round(precision*100, 2)}%")
    print(f"  F1-Score: {round(f1*100, 2)}%")
    print(f"  ROC-AUC: {round(auc*100, 2)}%")

#----------------------------------------------
#7. EXPORTACIÓN DE ENTREGABLES PARA POWER BI
#----------------------------------------------

print("\nExportando resultados analíticos para Microsoft Power BI...")
df_powerbi = X_test.copy()
df_powerbi['Real_isFraud'] = y_test
df_powerbi['Pred_LogisticRegression'] = lr_preds
df_powerbi['Pred_RandomForest'] = rf_preds
df_powerbi['Pred_IsolationForest'] = if_preds_binary
df_powerbi['AnomalyScore_IF'] = -if_scores

df_powerbi.to_csv("Resulatos_de_modelos_para_PowerBI.csv", index=False)
print(f"Archivo 'Resultados_de_modelos_para_PowerBI.csv' generado con éxito.")