# -*- coding: utf-8 -*-
"""Matrizes de confusion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQ4fPBStKzkshAiwM_QCwcqvMhyGKpTK
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import matplotlib.colors as mcolors

# Carga de datos
df = pd.read_csv('Resultados_de_modelos_para_PowerBI.csv')

# --- Diagnóstico: Imprimir las columnas del DataFrame para verificar el nombre correcto ---
print("Columnas disponibles en el DataFrame:", df.columns)
# ---------------------------------------------------------------------------------------

modelos = {
    'Regresión Logística': 'Pred_LogisticRegression',
    'Random Forest': 'Pred_RandomForest',
    'Isolation Forest': 'Pred_IsolationForest'
}

# Definir un mapa de colores personalizado: Rojo para error, Azul para acierto
# Índices: [0,0]=VN (Azul), [0,1]=FP (Rojo), [1,0]=FN (Rojo), [1,1]=VP (Azul)
def plot_custom_cm(model_name, col_name, ax):
    # Corrected column name from 'real_isfraud' to 'Real_isFraud'
    cm = confusion_matrix(df['Real_isFraud'], df[col_name])

    # Crear una paleta personalizada donde los errores (FP, FN) sean rojos
    # y los aciertos (VN, VP) sean azules
    custom_cmap = mcolors.LinearSegmentedColormap.from_list("", ["#d9e6f2", "#ffcccb"])

    # Usamos annot_kws para controlar el tamaño de fuente
    sns.heatmap(cm, annot=True, fmt='d', cmap='coolwarm_r', ax=ax,
                cbar=False, annot_kws={"size": 14})

    ax.set_title(f'{model_name}', fontsize=14, fontweight='bold')
    ax.set_xlabel('Predicción', fontsize=12)
    ax.set_ylabel('Realidad', fontsize=12)

# Crear la figura
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

for i, (nombre, col) in enumerate(modelos.items()):
    plot_custom_cm(nombre, col, axes[i])

plt.suptitle('Matrices de Confusión: Distribución de Aciertos (Azul) y Errores (Rojo)', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.savefig('Matrices_Confusion_Final.png', dpi=300)
plt.show()