# -*- coding: utf-8 -*-
"""SMOTE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eBU1e0oG2BDXYWbuszElggKTFdlq7LFc
"""

# 1. Importar las librerías necesarias
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

# 2. Cargar el conjunto de datos
# NOTA: Cambia 'dataset_paysim.csv' por el nombre o ruta exacta de tu archivo original
print("1. Cargando el dataset...")
df = pd.read_csv('PAYSIM.csv')

# 3. Preprocesamiento de los datos (Preparación para el modelo)
print("2. Preprocesando los datos...")
# Eliminar columnas identificadoras que no aportan al patrón (o son strings)
columnas_a_eliminar = ['step', 'nameOrig', 'nameDest', 'isFlaggedFraud']
df = df.drop(columns=[col for col in columnas_a_eliminar if col in df.columns], errors='ignore')

# Convertir la columna categórica 'type' (CASH_IN, CASH_OUT, TRANSFER, etc.) a valores numéricos
if 'type' in df.columns:
    df = pd.get_dummies(df, columns=['type'], drop_first=True)

# 4. Separar las características (X) y la etiqueta objetivo (y)
X = df.drop('isFraud', axis=1)
y = df['isFraud']

# Manejar valores NaN en la etiqueta objetivo 'y'
# Eliminar las filas donde 'y' es NaN, asegurando que X e y sigan alineados.
nan_in_y = y.isnull()
if nan_in_y.any():
    print("WARNING: Se encontraron valores NaN en la columna 'isFraud' (etiqueta objetivo). Se eliminarán las filas correspondientes.")
    X = X[~nan_in_y]
    y = y[~nan_in_y]

# 5. División en Entrenamiento (80%) y Prueba (20%)
print("3. Dividiendo los datos en Entrenamiento y Prueba...")
# stratify=y es crucial para mantener la proporción de fraudes en ambos sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# ---> AQUÍ EXTRAEMOS LOS DATOS LA TABLA "ANTES DE SMOTE" <---
print("\n" + "="*50)
print("TABLA 4.B: DISTRIBUCIÓN ORIGINAL EN ENTRENAMIENTO")
print("="*50)
legitimas_orig = (y_train == 0).sum()
fraudes_orig = (y_train == 1).sum()
print(f"Transacciones Legítimas : {legitimas_orig}")
print(f"Fraudes Reales          : {fraudes_orig}")
print(f"TOTAL                   : {legitimas_orig + fraudes_orig}")

# 6. Aplicar SMOTE (Exclusivamente al set de entrenamiento)
print("\n4. Aplicando SMOTE...")
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# ---> AQUÍ EXTRAEMOS LOS DATOS PARA LA TABLA "DESPUÉS DE SMOTE" <---
print("\n" + "="*50)
print("TABLA 4: DISTRIBUCIÓN TRAS APLICAR SMOTE")
print("="*50)
legitimas_smote = (y_train_resampled == 0).sum()
fraudes_smote = (y_train_resampled == 1).sum()
print(f"Transacciones Legítimas : {legitimas_smote}")
print(f"Fraudes (Reales + Sint.): {fraudes_smote}")
print(f"TOTAL                   : {legitimas_smote + fraudes_smote}")
print("="*50)