# -*- coding: utf-8 -*-
"""Tabla Comparativa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zE5eLEUBY1CCuHyi-u0zoHUhDoMGzsVw
"""

import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix

# 1. Carga del archivo
df = pd.read_csv('Resultados_de_modelos_para_PowerBI.csv')

# Definir los modelos
modelos = {
    'Random Forest': 'Pred_RandomForest',
    'Regresión Logística': 'Pred_LogisticRegression',
    'Isolation Forest': 'Pred_IsolationForest'
}

resultados = []

# 2. Cálculo de métricas
for nombre, columna in modelos.items():
    y_true = df['Real_isFraud'] # Using the corrected column name
    y_pred = df[columna]

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    resultados.append({
        'Modelo': nombre,
        'Precision': precision_score(y_true, y_pred, zero_division=0),
        'Recall': recall_score(y_true, y_pred, zero_division=0),
        'F1-score': f1_score(y_true, y_pred, zero_division=0),
        'ROC-AUC': roc_auc_score(y_true, y_pred),
        'Falsos Positivos': fp,
        'Falsos Negativos': fn,
        'Observaciones': "Desempeño óptimo" if fp < 50 else "Alta tasa de FP"
    })

# 3. Crear DataFrame y formatear
tabla_final = pd.DataFrame(resultados)
print(tabla_final.to_markdown(index=False))

# Opcional: Guardar para tu tesis
tabla_final.to_csv('Tabla_Comparativa_Tesis.csv', index=False)